name: stClinic
channels:
  - pyg
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - aom=3.3.0
  - backports=1.0
  - backports.zoneinfo=0.2.1
  - binutils_impl_linux-64=2.40
  - blas=2.116
  - blas-devel=3.9.0
  - brotli-python=1.0.9
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.11.17
  - cairo=1.16.0
  - certifi=2023.11.17
  - cffi=1.15.1
  - charset-normalizer=3.1.0
  - colorama=0.4.6
  - cudatoolkit=11.3.1
  - curl=7.86.0
  - expat=2.5.0
  - faiss=1.7.4
  - faiss-gpu=1.7.4
  - ffmpeg=4.3
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - fribidi=1.0.10
  - gcc_impl_linux-64=13.1.0
  - gettext=0.21.1
  - gfortran_impl_linux-64=13.1.0
  - gmp=6.2.1
  - gnutls=3.6.13
  - graphite2=1.3.13
  - gsl=2.7
  - gxx_impl_linux-64=13.1.0
  - harfbuzz=6.0.0
  - icu=70.1
  - idna=3.4
  - jinja2=3.1.2
  - joblib=1.3.0
  - jpeg=9e
  - kernel-headers_linux-64=2.6.32
  - keyutils=1.6.1
  - krb5=1.19.3
  - lame=3.100
  - lcms2=2.14
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.86.0
  - libdeflate=1.14
  - libdrm=2.4.114
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.5.0
  - libfaiss=1.7.4
  - libfaiss-avx2=1.7.4
  - libffi=3.4.2
  - libgcc-devel_linux-64=13.1.0
  - libgcc-ng=13.1.0
  - libgfortran-ng=13.1.0
  - libgfortran5=13.1.0
  - libglib=2.76.4
  - libgomp=13.1.0
  - libhwloc=2.9.1
  - libiconv=1.17
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnghttp2=1.52.0
  - libnsl=2.0.0
  - libopenblas=0.3.23
  - libpciaccess=0.17
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libsanitizer=13.1.0
  - libsqlite=3.42.0
  - libssh2=1.11.0
  - libstdcxx-devel_linux-64=13.1.0
  - libstdcxx-ng=13.1.0
  - libtiff=4.4.0
  - libuuid=2.38.1
  - libva=2.18.0
  - libvpx=1.11.0
  - libwebp-base=1.3.1
  - libxcb=1.13
  - libxml2=2.10.3
  - libzlib=1.2.13
  - llvm-openmp=16.0.6
  - make=4.3
  - markupsafe=2.1.3
  - mkl=2022.1.0
  - mkl-devel=2022.1.0
  - mkl-include=2022.1.0
  - ncurses=6.4
  - nettle=3.6
  - ninja=1.11.1
  - openblas=0.3.23
  - openh264=2.1.1
  - openjpeg=2.5.0
  - openssl=3.2.0
  - packaging=23.1
  - pango=1.50.14
  - pcre2=10.40
  - pillow=9.2.0
  - pip=23.1.2
  - pixman=0.40.0
  - platformdirs=3.8.0
  - pooch=1.7.0
  - psutil=5.9.5
  - pthread-stubs=0.4
  - pycparser=2.21
  - pyg=2.3.0
  - pysocks=1.7.1
  - python=3.8.17
  - python_abi=3.8
  - pytorch=1.12.0
  - pytorch-mutex=1.0
  - pytz=2023.3
  - r-base=4.0.5
  - readline=8.2
  - requests=2.31.0
  - rpy2=3.5.1
  - scikit-learn=1.3.0
  - scipy=1.10.1
  - sed=4.8
  - setuptools=68.0.0
  - simplegeneric=0.8.1
  - sleef=3.5.1
  - svt-av1=1.1.0
  - sysroot_linux-64=2.12
  - tbb=2021.9.0
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - tktable=2.10
  - torchaudio=0.12.0
  - torchvision=0.13.0
  - tqdm=4.65.0
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - tzlocal=5.0.1
  - urllib3=2.0.3
  - wheel=0.40.0
  - x264=1!161.3030
  - x265=3.5
  - xorg-fixesproto=5.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.3.0
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - anndata==0.9.2
    - astor==0.8.1
    - autograd==1.6.2
    - autograd-gamma==0.5.0
    - contourpy==1.1.0
    - cycler==0.11.0
    - fonttools==4.42.0
    - formulaic==0.6.5
    - future==0.18.3
    - graphlib-backport==1.0.3
    - h5py==3.9.0
    - hnswlib==0.5.1
    - igraph==0.10.8
    - importlib-metadata==6.8.0
    - importlib-resources==6.0.0
    - interface-meta==1.3.0
    - kiwisolver==1.4.4
    - lifelines==0.27.8
    - llvmlite==0.40.1
    - louvain==0.8.1
    - matplotlib==3.7.2
    - natsort==8.4.0
    - networkx==3.1
    - numba==0.57.1
    - numpy==1.22.3
    - pandas==1.5.3
    - patsy==0.5.3
    - pyg-lib==0.2.0+pt112cu113
    - pynndescent==0.5.10
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - python-igraph==0.10.8
    - scanpy==1.9.3
    - seaborn==0.11.2
    - session-info==1.0.0
    - six==1.16.0
    - statannotations==0.6.0
    - statsmodels==0.14.0
    - stdlib-list==0.9.0
    - texttable==1.6.7
    - torch-cluster==1.6.1
    - torch-scatter==2.1.1
    - torch-sparse==0.6.17
    - torch-spline-conv==1.2.2
    - tzdata==2023.3
    - umap-learn==0.5.3
    - wrapt==1.15.0
    - zipp==3.16.2